config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_session#new'

  post 'login' => 'user_session#create'

  get 'logout' => 'user_session#destroy', :as => 'log_out'

  resources :users

  resources :messages

  resources :inbox

  root 'user_session#login'

end

app/controllers/user_session_controller.rb
require 'openssl'
class UserSessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:user_session][:name].downcase)
    if @user && @user.authenticate(params[:user_session][:password])
      log_in(@user)

      response = HTTParty.get("http://#{$SERVER_IP}/#{@user.name}")

      if response.code === 200
        iteration = 10000

        digest = OpenSSL::Digest::SHA256.new

        masterkey = OpenSSL::PKCS5.pbkdf2_hmac(params[:user_session][:password], Base64.strict_decode64(response["salt_masterkey"]), iteration, 256, digest)

        $pubkey_user = OpenSSL::PKey::RSA.new(Base64.strict_decode64(response["pubkey_user"]))

        decipher = OpenSSL::Cipher::AES.new(128, :ECB)
        decipher.decrypt
        decipher.padding = 0
        decipher.key = masterkey

        privkey_user_enc_plane = Base64.strict_decode64(response["privkey_user_enc"])
        privkey_user_enc = decipher.update(privkey_user_enc_plane) + decipher.final
      
        $privkey_user = OpenSSL::PKey::RSA.new(privkey_user_enc, masterkey)

        flash[:notice] = "Statuscode: 200, Nachricht: Benutzerdaten wurden abgerufen."
        redirect_to messages_url, :notice => "Willkommen, #{@user.name}"
  	  else
        redirect_to root_url, :notice => "Nachricht: Benutzerdaten konnte nicht abgerufen werden!"
      end
    else
  		redirect_to root_url, :notice => "Benutzername oder Passwort stimmen nicht überein!"
  	end
  end

  def destroy
    log_out
  end
end

app/helpers/user_session_helper.rb
module UserSessionHelper

  #user log in
  def log_in(user)
    session[:user_id] = user.id
  end

  #check if user is logged_in
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
    redirect_to ''
  end
end

app/views/user_session/login.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Anmelden</div>
      <div class="panel-body">
        <%= form_for(:user_session, url: login_path) do |f| %>
          <div class="form-group">
              <%= f.label :name%><br>
              <%= f.text_field :name, class: "form-control"%>
          </div>
          <div class="form-group">
              <%= f.label :password%><br>
              <%= f.password_field :password, class: "form-control" %>
          </div>
          
          <div class="form-group">
              <%= f.submit "Anmelden", class: "btn btn-primary btn-sm" %>
              <%= link_to "Registrieren", new_user_path, class: "btn btn-default btn-sm" %>
          </div>
        <% end %>
      </div>
    </div>  
  </div>
  <div class="col-md-3"></div>
  </div>
</div>