config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'user_session#new'

  post 'login' => 'user_session#create'

  get 'logout' => 'user_session#destroy', :as => 'log_out'

  resources :users

  resources :messages

  resources :inbox

  root 'user_session#login'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password	

	validates :password, length: { :minimum => 6 }
	validates :name, presence: true
	validates :name, format: { without: /\s/ }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

      salt_masterkey = OpenSSL::Random.random_bytes 64

      iteration = 10000

      digest = OpenSSL::Digest::SHA256.new

      masterkey = OpenSSL::PKCS5.pbkdf2_hmac(user_params[:password], salt_masterkey, iteration, 256, digest)

      keys = OpenSSL::PKey::RSA.new 2048
      $privkey_user = keys.to_pem

      cipher = OpenSSL::Cipher.new('AES-128-ECB')
      cipher.encrypt
      cipher.key = masterkey
      privkey_user_enc = cipher.update($privkey_user) + cipher.final

      response = HTTParty.post("http://#{$SERVER_IP}/user",
                :body => { 
                          :user => { 
                             :username => @user.name,
                             :salt_masterkey => Base64.strict_encode64(salt_masterkey),
                             :pubkey_user => Base64.strict_encode64(keys.public_key.to_pem),
                             :privkey_user_enc => Base64.strict_encode64(privkey_user_enc)
                           }
                          }.to_json,
                :headers => { 'Content-Type' => 'application/json'})

    if response.code === 201 
      @user.save
      redirect_to ''
    else
      if response.code === 422
      flash[:notice] = "Statuscode: 422, Speichern fehlgeschlagen."
      redirect_to new_user_path
      elsif response.code === 400
        flash[:notice] = "Statuscode: 400, Fehler in der Syntax."
        redirect_to new_user_path
      elsif response.code === 409
        flash[:notice] = "Statuscode: 409, Username bereits vergeben."
        redirect_to new_user_path
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name,  class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password,  class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Registrieren", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "btn btn-default btn-xs"%> |
<%= link_to 'Back', class: "btn btn-default btn-xs" ,users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--%= link_to 'New User', new_user_path %>-->

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Registrieren</div>
      <div class="panel-body">

		<%= render 'form' %>
      </div>
    </div>
        <%= link_to 'Zurück', root_path, class: "btn btn-default btn-xs" %>  
  </div>
  <div class="col-md-3"></div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>